// Copyright 2024 Nic, Vlad, Alex

#pragma once

#include "NativeGameplayTags.h"

namespace AsymGameplayTags
{
	/*
	*	Input Tags 
	*/
	ASYMPTOMAGICKAL_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ASYMPTOMAGICKAL_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	ASYMPTOMAGICKAL_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	ASYMPTOMAGICKAL_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);

	/*
	 *	UI Layers
	 */
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_PopUp);
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_HUD);

	/*
	 *	Tile Tags
	 */
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tile_Permission_Locked);
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tile_Permission_OnlyKing);
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tile_Permission_OnlyPlayers);
	ASYMPTOMAGICKAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tile_Permission_All);
	
}
